name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch that is being deployed. Should be a branch on the given repository
        required: false
        default: main
      repository:
        description: The {owner}/{repository} that is being deployed.
        required: false
        default: World-Hunters-Association/Solo-Leveling-Simulator

jobs:
  build:
    name: Deploy
    runs-on: [self-hosted, sls-test]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Stop process
        run: pm2 stop sls
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repository || 'World-Hunters-Association/Solo-Leveling-Simulator' }}
          ref: ${{ github.event.inputs.ref || 'main' }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@dbe1369d7be17e7823f8c1ee1ae8bec5779239dd # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Locate source
        run: cd ~/test/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:p
      # - name: Prune Dev-dependencies
      #   run: npm prune --production
